Repository Abidsyed25/ScrapQuest, pull requests merged in 2024-07, with the labels that each got.

#136 Added Icons to Footer
  components/Footer.tsx
Labels: gssoc, level1

#138 FAQ page made
  app/faq/faqs.js
  app/faq/page.tsx
  components.json
  components/ui/accordion.tsx
  lib/utils.ts
  package-lock.json
  package.json
Labels: gssoc, level2

#142 Issue#132 fixed. Added Terms and Conditions Page
  app/termsconditions/page.tsx
  components/Footer.tsx
  package-lock.json
Labels: gssoc, level2

#146 Refine Terms & Conditions Page Styling and Add Navbar Icon
  app/termsconditions/page.tsx
  components/Nav.tsx
Labels: gssoc, level2

#149 fixed footer issue and also footer responsiveness issue
  components/Footer.tsx
  components/Nav.tsx
Labels: gssoc, level2

#151 Footer added in all pages
  app/about/page.tsx
  app/contact/page.tsx
  app/faq/page.tsx
  app/termsconditions/page.tsx
Labels: gssoc, level1

#158 Resolve issue #152
  components/Nav.tsx
Labels: gssoc, level2

#163 Updated readme.md
  README.md
Labels: gssoc

#160 Made Hero & its associated components responsive
  components/Form.tsx
  components/Hero.tsx
  components/HeroTypingEffect.tsx
  components/ui/TypeWriter.tsx
Labels: gssoc, level2

#161 Added Privacy Policy Page
  app/privacypolicy/page.tsx
  components/Footer.tsx
Labels: gssoc, level2

#162 Adding MultiLanguage Facility and Enhancing Navbar
  app/GoogleTranslate.css
  app/GoogleTranslate.tsx
  app/globals.css
  app/layout.tsx
  app/login/page.tsx
  components/HeroTypingEffect.tsx
  components/Nav.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: gssoc, level2

#169 Adding Chatbot to Website and setting the Privacy Policy Page
  app/layout.tsx
  app/privacypolicy/homeicon.png
  app/privacypolicy/page.tsx
  components/Footer.tsx
  components/Nav.tsx
Labels: gssoc, level3

#174 redesigned the footer
  components/Footer.tsx
Labels: gssoc, level3

#175 Contact Us Redesigned
  app/contact/contact.jpg
  app/contact/page.tsx
Labels: gssoc, level2

#181 styled the navbar
  components/Nav.tsx
Labels: gssoc, level2

#182 Adding Google Authentication Using Firebase
  app/Firebase/firebase.js
  app/login/page.tsx
  firebase.json
  package-lock.json
  package.json
  tsconfig.json
Labels: gssoc, level2

#185 Issue #183 fixed. The language translator is now visible properly.
  app/GoogleTranslate.css
  app/GoogleTranslate.tsx
Labels: gssoc, level2

#192 Adding Github Authentication Using Firebase
  app/Firebase/firebase.js
  app/login/page.tsx
Labels: gssoc, level2

#194 Updated twitter icon
  app/contact/page.tsx
  app/login/page.tsx
  components/Footer.tsx
  package-lock.json
  package.json
Labels: gssoc, level1

#196 ✔️Improved the "FAQ Page" of ScrapQuest !
  app/faq/faq.css
  app/faq/faqs.js
  app/faq/page.tsx
Labels: gssoc, level2

#197 enhanced the privacy policy page
  app/privacypolicy/page.tsx
Labels: gssoc, level2

#199 Added dynamic copyright year
  components/Footer.tsx
Labels: gssoc, level1

#204 Adding Facebook Authentication
  app/Firebase/firebase.js
  app/login/page.tsx
Labels: gssoc, level2

#207 Enhanced the contact form
  app/contact/page.tsx
Labels: gssoc, level2

#201 ✔️ Implemented a Dedicated Licensing page.
  app/licensing/homeicon.png
  app/licensing/licensing.module.css
  app/licensing/page.tsx
  components/Footer.tsx
Labels: gssoc, level2

#212 Adding Twitter Authentication
  app/Firebase/firebase.js
  app/login/page.tsx
Labels: gssoc, level2

#213 ✔️Styled the "Vertical Scrollbar" in Website
  app/globals.css
  app/page.tsx
  components/CustomScrollbar.module.css
  components/CustomScrollbar.tsx
Labels: gssoc, level2

#214 Improved the Styling of About Us Page
  app/about/page.tsx
Labels: gssoc, level2

#215 ✔️Added Smooth Hovering effects to the Links in Footer.
  app/Footer.module.css
  components/Footer.tsx
Labels: gssoc, level2

#217 Enhanced the terms and conditions page
  app/termsconditions/page.tsx
Labels: gssoc, level2
